// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: snapshot.proto

package kvserverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_KIND_KV              Kind = 0
	Kind_KIND_TXN             Kind = 1
	Kind_KIND_LEASE_GRANT     Kind = 2
	Kind_KIND_LEASE_REVOKE    Kind = 3
	Kind_KIND_LEASE_KEEPALIVE Kind = 4
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_KV",
		1: "KIND_TXN",
		2: "KIND_LEASE_GRANT",
		3: "KIND_LEASE_REVOKE",
		4: "KIND_LEASE_KEEPALIVE",
	}
	Kind_value = map[string]int32{
		"KIND_KV":              0,
		"KIND_TXN":             1,
		"KIND_LEASE_GRANT":     2,
		"KIND_LEASE_REVOKE":    3,
		"KIND_LEASE_KEEPALIVE": 4,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_snapshot_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{0}
}

type Revision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Main          int64                  `protobuf:"varint,1,opt,name=main,proto3" json:"main,omitempty"`
	Sub           int64                  `protobuf:"varint,2,opt,name=sub,proto3" json:"sub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revision) Reset() {
	*x = Revision{}
	mi := &file_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revision) ProtoMessage() {}

func (x *Revision) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revision.ProtoReflect.Descriptor instead.
func (*Revision) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *Revision) GetMain() int64 {
	if x != nil {
		return x.Main
	}
	return 0
}

func (x *Revision) GetSub() int64 {
	if x != nil {
		return x.Sub
	}
	return 0
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Revision      int64                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValue) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          Kind                   `protobuf:"varint,1,opt,name=kind,proto3,enum=kvserverpb.Kind" json:"kind,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Err           string                 `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`
	Rev           *Revision              `protobuf:"bytes,5,opt,name=rev,proto3" json:"rev,omitempty"`
	Value         []byte                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,7,opt,name=found,proto3" json:"found,omitempty"`
	TxnSucceeded  bool                   `protobuf:"varint,8,opt,name=txn_succeeded,json=txnSucceeded,proto3" json:"txn_succeeded,omitempty"`
	TxnResults    []*KeyValue            `protobuf:"bytes,9,rep,name=txn_results,json=txnResults,proto3" json:"txn_results,omitempty"`
	LeaseId       int64                  `protobuf:"varint,10,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LeaseTtl      int64                  `protobuf:"varint,11,opt,name=lease_ttl,json=leaseTtl,proto3" json:"lease_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_KV
}

func (x *Result) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Result) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Result) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *Result) GetRev() *Revision {
	if x != nil {
		return x.Rev
	}
	return nil
}

func (x *Result) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Result) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *Result) GetTxnSucceeded() bool {
	if x != nil {
		return x.TxnSucceeded
	}
	return false
}

func (x *Result) GetTxnResults() []*KeyValue {
	if x != nil {
		return x.TxnResults
	}
	return nil
}

func (x *Result) GetLeaseId() int64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

func (x *Result) GetLeaseTtl() int64 {
	if x != nil {
		return x.LeaseTtl
	}
	return 0
}

type ServerSnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	KvSnapshot       []byte                 `protobuf:"bytes,1,opt,name=kv_snapshot,json=kvSnapshot,proto3" json:"kv_snapshot,omitempty"`
	ClientLastSeq    map[int64]int64        `protobuf:"bytes,2,rep,name=client_last_seq,json=clientLastSeq,proto3" json:"client_last_seq,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ClientLastResult map[int64]*Result      `protobuf:"bytes,3,rep,name=client_last_result,json=clientLastResult,proto3" json:"client_last_result,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServerSnapshot) Reset() {
	*x = ServerSnapshot{}
	mi := &file_snapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSnapshot) ProtoMessage() {}

func (x *ServerSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSnapshot.ProtoReflect.Descriptor instead.
func (*ServerSnapshot) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *ServerSnapshot) GetKvSnapshot() []byte {
	if x != nil {
		return x.KvSnapshot
	}
	return nil
}

func (x *ServerSnapshot) GetClientLastSeq() map[int64]int64 {
	if x != nil {
		return x.ClientLastSeq
	}
	return nil
}

func (x *ServerSnapshot) GetClientLastResult() map[int64]*Result {
	if x != nil {
		return x.ClientLastResult
	}
	return nil
}

var File_snapshot_proto protoreflect.FileDescriptor

const file_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x0esnapshot.proto\x12\n" +
	"kvserverpb\"0\n" +
	"\bRevision\x12\x12\n" +
	"\x04main\x18\x01 \x01(\x03R\x04main\x12\x10\n" +
	"\x03sub\x18\x02 \x01(\x03R\x03sub\"N\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\"\xd7\x02\n" +
	"\x06Result\x12$\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x10.kvserverpb.KindR\x04kind\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x10\n" +
	"\x03err\x18\x04 \x01(\tR\x03err\x12&\n" +
	"\x03rev\x18\x05 \x01(\v2\x14.kvserverpb.RevisionR\x03rev\x12\x14\n" +
	"\x05value\x18\x06 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\a \x01(\bR\x05found\x12#\n" +
	"\rtxn_succeeded\x18\b \x01(\bR\ftxnSucceeded\x125\n" +
	"\vtxn_results\x18\t \x03(\v2\x14.kvserverpb.KeyValueR\n" +
	"txnResults\x12\x19\n" +
	"\blease_id\x18\n" +
	" \x01(\x03R\aleaseId\x12\x1b\n" +
	"\tlease_ttl\x18\v \x01(\x03R\bleaseTtl\"\x83\x03\n" +
	"\x0eServerSnapshot\x12\x1f\n" +
	"\vkv_snapshot\x18\x01 \x01(\fR\n" +
	"kvSnapshot\x12U\n" +
	"\x0fclient_last_seq\x18\x02 \x03(\v2-.kvserverpb.ServerSnapshot.ClientLastSeqEntryR\rclientLastSeq\x12^\n" +
	"\x12client_last_result\x18\x03 \x03(\v20.kvserverpb.ServerSnapshot.ClientLastResultEntryR\x10clientLastResult\x1a@\n" +
	"\x12ClientLastSeqEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aW\n" +
	"\x15ClientLastResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.kvserverpb.ResultR\x05value:\x028\x01*h\n" +
	"\x04Kind\x12\v\n" +
	"\aKIND_KV\x10\x00\x12\f\n" +
	"\bKIND_TXN\x10\x01\x12\x14\n" +
	"\x10KIND_LEASE_GRANT\x10\x02\x12\x15\n" +
	"\x11KIND_LEASE_REVOKE\x10\x03\x12\x18\n" +
	"\x14KIND_LEASE_KEEPALIVE\x10\x04B Z\x1eetcd-KV/internal/pb/kvserverpbb\x06proto3"

var (
	file_snapshot_proto_rawDescOnce sync.Once
	file_snapshot_proto_rawDescData []byte
)

func file_snapshot_proto_rawDescGZIP() []byte {
	file_snapshot_proto_rawDescOnce.Do(func() {
		file_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshot_proto_rawDesc), len(file_snapshot_proto_rawDesc)))
	})
	return file_snapshot_proto_rawDescData
}

var file_snapshot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_snapshot_proto_goTypes = []any{
	(Kind)(0),              // 0: kvserverpb.Kind
	(*Revision)(nil),       // 1: kvserverpb.Revision
	(*KeyValue)(nil),       // 2: kvserverpb.KeyValue
	(*Result)(nil),         // 3: kvserverpb.Result
	(*ServerSnapshot)(nil), // 4: kvserverpb.ServerSnapshot
	nil,                    // 5: kvserverpb.ServerSnapshot.ClientLastSeqEntry
	nil,                    // 6: kvserverpb.ServerSnapshot.ClientLastResultEntry
}
var file_snapshot_proto_depIdxs = []int32{
	0, // 0: kvserverpb.Result.kind:type_name -> kvserverpb.Kind
	1, // 1: kvserverpb.Result.rev:type_name -> kvserverpb.Revision
	2, // 2: kvserverpb.Result.txn_results:type_name -> kvserverpb.KeyValue
	5, // 3: kvserverpb.ServerSnapshot.client_last_seq:type_name -> kvserverpb.ServerSnapshot.ClientLastSeqEntry
	6, // 4: kvserverpb.ServerSnapshot.client_last_result:type_name -> kvserverpb.ServerSnapshot.ClientLastResultEntry
	3, // 5: kvserverpb.ServerSnapshot.ClientLastResultEntry.value:type_name -> kvserverpb.Result
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_snapshot_proto_init() }
func file_snapshot_proto_init() {
	if File_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshot_proto_rawDesc), len(file_snapshot_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snapshot_proto_goTypes,
		DependencyIndexes: file_snapshot_proto_depIdxs,
		EnumInfos:         file_snapshot_proto_enumTypes,
		MessageInfos:      file_snapshot_proto_msgTypes,
	}.Build()
	File_snapshot_proto = out.File
	file_snapshot_proto_goTypes = nil
	file_snapshot_proto_depIdxs = nil
}
