// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mvcc/kv_store.proto

package mvcc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentRev    int64                  `protobuf:"varint,1,opt,name=current_rev,json=currentRev,proto3" json:"current_rev,omitempty"`
	Entries       []*KeyEntry            `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_mvcc_kv_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_mvcc_kv_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_mvcc_kv_store_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetCurrentRev() int64 {
	if x != nil {
		return x.CurrentRev
	}
	return 0
}

func (x *Snapshot) GetEntries() []*KeyEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type KeyEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Revisions     []*ValueRevision       `protobuf:"bytes,2,rep,name=revisions,proto3" json:"revisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyEntry) Reset() {
	*x = KeyEntry{}
	mi := &file_mvcc_kv_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyEntry) ProtoMessage() {}

func (x *KeyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_mvcc_kv_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyEntry.ProtoReflect.Descriptor instead.
func (*KeyEntry) Descriptor() ([]byte, []int) {
	return file_mvcc_kv_store_proto_rawDescGZIP(), []int{1}
}

func (x *KeyEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyEntry) GetRevisions() []*ValueRevision {
	if x != nil {
		return x.Revisions
	}
	return nil
}

type ValueRevision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rev           *Revision              `protobuf:"bytes,1,opt,name=rev,proto3" json:"rev,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Deleted       bool                   `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueRevision) Reset() {
	*x = ValueRevision{}
	mi := &file_mvcc_kv_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueRevision) ProtoMessage() {}

func (x *ValueRevision) ProtoReflect() protoreflect.Message {
	mi := &file_mvcc_kv_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueRevision.ProtoReflect.Descriptor instead.
func (*ValueRevision) Descriptor() ([]byte, []int) {
	return file_mvcc_kv_store_proto_rawDescGZIP(), []int{2}
}

func (x *ValueRevision) GetRev() *Revision {
	if x != nil {
		return x.Rev
	}
	return nil
}

func (x *ValueRevision) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ValueRevision) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type Revision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Main          int64                  `protobuf:"varint,1,opt,name=main,proto3" json:"main,omitempty"`
	Sub           int64                  `protobuf:"varint,2,opt,name=sub,proto3" json:"sub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revision) Reset() {
	*x = Revision{}
	mi := &file_mvcc_kv_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revision) ProtoMessage() {}

func (x *Revision) ProtoReflect() protoreflect.Message {
	mi := &file_mvcc_kv_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revision.ProtoReflect.Descriptor instead.
func (*Revision) Descriptor() ([]byte, []int) {
	return file_mvcc_kv_store_proto_rawDescGZIP(), []int{3}
}

func (x *Revision) GetMain() int64 {
	if x != nil {
		return x.Main
	}
	return 0
}

func (x *Revision) GetSub() int64 {
	if x != nil {
		return x.Sub
	}
	return 0
}

var File_mvcc_kv_store_proto protoreflect.FileDescriptor

const file_mvcc_kv_store_proto_rawDesc = "" +
	"\n" +
	"\x13mvcc/kv_store.proto\x12\x04mvcc\"U\n" +
	"\bSnapshot\x12\x1f\n" +
	"\vcurrent_rev\x18\x01 \x01(\x03R\n" +
	"currentRev\x12(\n" +
	"\aentries\x18\x02 \x03(\v2\x0e.mvcc.KeyEntryR\aentries\"O\n" +
	"\bKeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\trevisions\x18\x02 \x03(\v2\x13.mvcc.ValueRevisionR\trevisions\"a\n" +
	"\rValueRevision\x12 \n" +
	"\x03rev\x18\x01 \x01(\v2\x0e.mvcc.RevisionR\x03rev\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\bR\adeleted\"0\n" +
	"\bRevision\x12\x12\n" +
	"\x04main\x18\x01 \x01(\x03R\x04main\x12\x10\n" +
	"\x03sub\x18\x02 \x01(\x03R\x03subB\x1aZ\x18etcd-KV/internal/pb/mvccb\x06proto3"

var (
	file_mvcc_kv_store_proto_rawDescOnce sync.Once
	file_mvcc_kv_store_proto_rawDescData []byte
)

func file_mvcc_kv_store_proto_rawDescGZIP() []byte {
	file_mvcc_kv_store_proto_rawDescOnce.Do(func() {
		file_mvcc_kv_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mvcc_kv_store_proto_rawDesc), len(file_mvcc_kv_store_proto_rawDesc)))
	})
	return file_mvcc_kv_store_proto_rawDescData
}

var file_mvcc_kv_store_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mvcc_kv_store_proto_goTypes = []any{
	(*Snapshot)(nil),      // 0: mvcc.Snapshot
	(*KeyEntry)(nil),      // 1: mvcc.KeyEntry
	(*ValueRevision)(nil), // 2: mvcc.ValueRevision
	(*Revision)(nil),      // 3: mvcc.Revision
}
var file_mvcc_kv_store_proto_depIdxs = []int32{
	1, // 0: mvcc.Snapshot.entries:type_name -> mvcc.KeyEntry
	2, // 1: mvcc.KeyEntry.revisions:type_name -> mvcc.ValueRevision
	3, // 2: mvcc.ValueRevision.rev:type_name -> mvcc.Revision
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mvcc_kv_store_proto_init() }
func file_mvcc_kv_store_proto_init() {
	if File_mvcc_kv_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mvcc_kv_store_proto_rawDesc), len(file_mvcc_kv_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mvcc_kv_store_proto_goTypes,
		DependencyIndexes: file_mvcc_kv_store_proto_depIdxs,
		MessageInfos:      file_mvcc_kv_store_proto_msgTypes,
	}.Build()
	File_mvcc_kv_store_proto = out.File
	file_mvcc_kv_store_proto_goTypes = nil
	file_mvcc_kv_store_proto_depIdxs = nil
}
