// raft 的序列化/反序列化操作
syntax = "proto3";

package raftpb;

option go_package = "etcd-KV/internal/pb/raftpb";

message Snapshot {
    int64 lastIncludeIndex = 1; // 下标
    int64 lastIncludeTerm = 2; // 快照中最后一条日志的任期
}

message LogEntry {
    int64 Term = 1; // 任期
    bytes Command = 2; // 命令内容
    int64 Index = 3; // 下标
}

// 核心状态
message HardState {
    int64 Term = 1;
    int64 VotedFor = 2;
}

message RaftState {
    Snapshot snapshot = 1;
    repeated LogEntry log = 2;
    HardState hardstate = 3;
}


service Raft {
    rpc AppendEntries(AppendEntriesRequest) returns (AppendEntriesReply);
    rpc RequestVote(RequestVoteRequest) returns (RequestVoteReply);
    rpc InstallSnapshot(InstallSnapshotRequest) returns (InstallSnapshotReply);
}

message AppendEntriesRequest {
    int64 term = 1;
    int64 leader_id = 2;
    int64 prev_log_index = 3;
    int64 prev_log_term = 4;
    repeated LogEntry entries = 5;
    int64 leader_commit = 6;
}
message AppendEntriesReply {
    int64 term = 1;
    bool success = 2;
    int64 conflict_term = 3;
    int64 conflict_index = 4;
}

message RequestVoteRequest {
    int64 term = 1;
    int64 candidate_id = 2;
    int64 last_log_index = 3;
    int64 last_log_term = 4;
}
message RequestVoteReply {
    int64 term = 1;
    bool vote_granted = 2;
}

message InstallSnapshotRequest {
    int64 term = 1;
    int64 leader_id = 2;
    int64 last_include_index = 3;
    int64 last_include_term = 4;
    bytes data = 5;
}
message InstallSnapshotReply {
    int64 term = 1;
}