// raft 的序列化/反序列化操作

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/pb/raftpb/raft.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LastIncludeIndex int64                  `protobuf:"varint,1,opt,name=lastIncludeIndex,proto3" json:"lastIncludeIndex,omitempty"` // 下标
	LastIncludeTerm  int64                  `protobuf:"varint,2,opt,name=lastIncludeTerm,proto3" json:"lastIncludeTerm,omitempty"`   // 快照中最后一条日志的任期
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_internal_pb_raftpb_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_raftpb_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_internal_pb_raftpb_raft_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetLastIncludeIndex() int64 {
	if x != nil {
		return x.LastIncludeIndex
	}
	return 0
}

func (x *Snapshot) GetLastIncludeTerm() int64 {
	if x != nil {
		return x.LastIncludeTerm
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`      // 任期
	Command       []byte                 `protobuf:"bytes,2,opt,name=Command,proto3" json:"Command,omitempty"` // 命令内容
	Index         int64                  `protobuf:"varint,3,opt,name=Index,proto3" json:"Index,omitempty"`    // 下标
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_internal_pb_raftpb_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_raftpb_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_internal_pb_raftpb_raft_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *LogEntry) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

// 核心状态
type HardState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	VotedFor      int64                  `protobuf:"varint,2,opt,name=VotedFor,proto3" json:"VotedFor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardState) Reset() {
	*x = HardState{}
	mi := &file_internal_pb_raftpb_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardState) ProtoMessage() {}

func (x *HardState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_raftpb_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardState.ProtoReflect.Descriptor instead.
func (*HardState) Descriptor() ([]byte, []int) {
	return file_internal_pb_raftpb_raft_proto_rawDescGZIP(), []int{2}
}

func (x *HardState) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *HardState) GetVotedFor() int64 {
	if x != nil {
		return x.VotedFor
	}
	return 0
}

type RaftState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Log           []*LogEntry            `protobuf:"bytes,2,rep,name=log,proto3" json:"log,omitempty"`
	Hardstate     *HardState             `protobuf:"bytes,3,opt,name=hardstate,proto3" json:"hardstate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftState) Reset() {
	*x = RaftState{}
	mi := &file_internal_pb_raftpb_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftState) ProtoMessage() {}

func (x *RaftState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_raftpb_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftState.ProtoReflect.Descriptor instead.
func (*RaftState) Descriptor() ([]byte, []int) {
	return file_internal_pb_raftpb_raft_proto_rawDescGZIP(), []int{3}
}

func (x *RaftState) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *RaftState) GetLog() []*LogEntry {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *RaftState) GetHardstate() *HardState {
	if x != nil {
		return x.Hardstate
	}
	return nil
}

var File_internal_pb_raftpb_raft_proto protoreflect.FileDescriptor

const file_internal_pb_raftpb_raft_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/pb/raftpb/raft.proto\x12\x06raftpb\"`\n" +
	"\bSnapshot\x12*\n" +
	"\x10lastIncludeIndex\x18\x01 \x01(\x03R\x10lastIncludeIndex\x12(\n" +
	"\x0flastIncludeTerm\x18\x02 \x01(\x03R\x0flastIncludeTerm\"N\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04Term\x18\x01 \x01(\x03R\x04Term\x12\x18\n" +
	"\aCommand\x18\x02 \x01(\fR\aCommand\x12\x14\n" +
	"\x05Index\x18\x03 \x01(\x03R\x05Index\";\n" +
	"\tHardState\x12\x12\n" +
	"\x04Term\x18\x01 \x01(\x03R\x04Term\x12\x1a\n" +
	"\bVotedFor\x18\x02 \x01(\x03R\bVotedFor\"\x8e\x01\n" +
	"\tRaftState\x12,\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x10.raftpb.SnapshotR\bsnapshot\x12\"\n" +
	"\x03log\x18\x02 \x03(\v2\x10.raftpb.LogEntryR\x03log\x12/\n" +
	"\thardstate\x18\x03 \x01(\v2\x11.raftpb.HardStateR\thardstateB\x1cZ\x1aetcd-KV/internal/pb/raftpbb\x06proto3"

var (
	file_internal_pb_raftpb_raft_proto_rawDescOnce sync.Once
	file_internal_pb_raftpb_raft_proto_rawDescData []byte
)

func file_internal_pb_raftpb_raft_proto_rawDescGZIP() []byte {
	file_internal_pb_raftpb_raft_proto_rawDescOnce.Do(func() {
		file_internal_pb_raftpb_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_raftpb_raft_proto_rawDesc), len(file_internal_pb_raftpb_raft_proto_rawDesc)))
	})
	return file_internal_pb_raftpb_raft_proto_rawDescData
}

var file_internal_pb_raftpb_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_pb_raftpb_raft_proto_goTypes = []any{
	(*Snapshot)(nil),  // 0: raftpb.Snapshot
	(*LogEntry)(nil),  // 1: raftpb.LogEntry
	(*HardState)(nil), // 2: raftpb.HardState
	(*RaftState)(nil), // 3: raftpb.RaftState
}
var file_internal_pb_raftpb_raft_proto_depIdxs = []int32{
	0, // 0: raftpb.RaftState.snapshot:type_name -> raftpb.Snapshot
	1, // 1: raftpb.RaftState.log:type_name -> raftpb.LogEntry
	2, // 2: raftpb.RaftState.hardstate:type_name -> raftpb.HardState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_pb_raftpb_raft_proto_init() }
func file_internal_pb_raftpb_raft_proto_init() {
	if File_internal_pb_raftpb_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_raftpb_raft_proto_rawDesc), len(file_internal_pb_raftpb_raft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_raftpb_raft_proto_goTypes,
		DependencyIndexes: file_internal_pb_raftpb_raft_proto_depIdxs,
		MessageInfos:      file_internal_pb_raftpb_raft_proto_msgTypes,
	}.Build()
	File_internal_pb_raftpb_raft_proto = out.File
	file_internal_pb_raftpb_raft_proto_goTypes = nil
	file_internal_pb_raftpb_raft_proto_depIdxs = nil
}
