// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: command.proto

package commandpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_KIND_KV              Kind = 0
	Kind_KIND_TXN             Kind = 1
	Kind_KIND_LEASE_GRANT     Kind = 2
	Kind_KIND_LEASE_REVOKE    Kind = 3
	Kind_KIND_LEASE_KEEPALIVE Kind = 4
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_KV",
		1: "KIND_TXN",
		2: "KIND_LEASE_GRANT",
		3: "KIND_LEASE_REVOKE",
		4: "KIND_LEASE_KEEPALIVE",
	}
	Kind_value = map[string]int32{
		"KIND_KV":              0,
		"KIND_TXN":             1,
		"KIND_LEASE_GRANT":     2,
		"KIND_LEASE_REVOKE":    3,
		"KIND_LEASE_KEEPALIVE": 4,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_command_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_command_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0}
}

type KVType int32

const (
	KVType_KV_PUT    KVType = 0
	KVType_KV_GET    KVType = 1
	KVType_KV_DELETE KVType = 2
)

// Enum value maps for KVType.
var (
	KVType_name = map[int32]string{
		0: "KV_PUT",
		1: "KV_GET",
		2: "KV_DELETE",
	}
	KVType_value = map[string]int32{
		"KV_PUT":    0,
		"KV_GET":    1,
		"KV_DELETE": 2,
	}
)

func (x KVType) Enum() *KVType {
	p := new(KVType)
	*p = x
	return p
}

func (x KVType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KVType) Descriptor() protoreflect.EnumDescriptor {
	return file_command_proto_enumTypes[1].Descriptor()
}

func (KVType) Type() protoreflect.EnumType {
	return &file_command_proto_enumTypes[1]
}

func (x KVType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KVType.Descriptor instead.
func (KVType) EnumDescriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{1}
}

type TxnCompareOp int32

const (
	TxnCompareOp_TXN_COMPARE_EQUAL   TxnCompareOp = 0
	TxnCompareOp_TXN_COMPARE_GREATER TxnCompareOp = 1
	TxnCompareOp_TXN_COMPARE_LESS    TxnCompareOp = 2
)

// Enum value maps for TxnCompareOp.
var (
	TxnCompareOp_name = map[int32]string{
		0: "TXN_COMPARE_EQUAL",
		1: "TXN_COMPARE_GREATER",
		2: "TXN_COMPARE_LESS",
	}
	TxnCompareOp_value = map[string]int32{
		"TXN_COMPARE_EQUAL":   0,
		"TXN_COMPARE_GREATER": 1,
		"TXN_COMPARE_LESS":    2,
	}
)

func (x TxnCompareOp) Enum() *TxnCompareOp {
	p := new(TxnCompareOp)
	*p = x
	return p
}

func (x TxnCompareOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxnCompareOp) Descriptor() protoreflect.EnumDescriptor {
	return file_command_proto_enumTypes[2].Descriptor()
}

func (TxnCompareOp) Type() protoreflect.EnumType {
	return &file_command_proto_enumTypes[2]
}

func (x TxnCompareOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxnCompareOp.Descriptor instead.
func (TxnCompareOp) EnumDescriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{2}
}

type TxnOpType int32

const (
	TxnOpType_TXN_OP_GET    TxnOpType = 0
	TxnOpType_TXN_OP_PUT    TxnOpType = 1
	TxnOpType_TXN_OP_DELETE TxnOpType = 2
)

// Enum value maps for TxnOpType.
var (
	TxnOpType_name = map[int32]string{
		0: "TXN_OP_GET",
		1: "TXN_OP_PUT",
		2: "TXN_OP_DELETE",
	}
	TxnOpType_value = map[string]int32{
		"TXN_OP_GET":    0,
		"TXN_OP_PUT":    1,
		"TXN_OP_DELETE": 2,
	}
)

func (x TxnOpType) Enum() *TxnOpType {
	p := new(TxnOpType)
	*p = x
	return p
}

func (x TxnOpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxnOpType) Descriptor() protoreflect.EnumDescriptor {
	return file_command_proto_enumTypes[3].Descriptor()
}

func (TxnOpType) Type() protoreflect.EnumType {
	return &file_command_proto_enumTypes[3]
}

func (x TxnOpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxnOpType.Descriptor instead.
func (TxnOpType) EnumDescriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{3}
}

type KVCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          KVType                 `protobuf:"varint,1,opt,name=type,proto3,enum=commandpb.KVType" json:"type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ClientId      int64                  `protobuf:"varint,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           int64                  `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	Rev           int64                  `protobuf:"varint,6,opt,name=rev,proto3" json:"rev,omitempty"`
	LeaseId       int64                  `protobuf:"varint,7,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVCommand) Reset() {
	*x = KVCommand{}
	mi := &file_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVCommand) ProtoMessage() {}

func (x *KVCommand) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVCommand.ProtoReflect.Descriptor instead.
func (*KVCommand) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0}
}

func (x *KVCommand) GetType() KVType {
	if x != nil {
		return x.Type
	}
	return KVType_KV_PUT
}

func (x *KVCommand) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVCommand) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KVCommand) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *KVCommand) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *KVCommand) GetRev() int64 {
	if x != nil {
		return x.Rev
	}
	return 0
}

func (x *KVCommand) GetLeaseId() int64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

type TxnCompare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Op            TxnCompareOp           `protobuf:"varint,2,opt,name=op,proto3,enum=commandpb.TxnCompareOp" json:"op,omitempty"`
	Revision      int64                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnCompare) Reset() {
	*x = TxnCompare{}
	mi := &file_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnCompare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnCompare) ProtoMessage() {}

func (x *TxnCompare) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnCompare.ProtoReflect.Descriptor instead.
func (*TxnCompare) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{1}
}

func (x *TxnCompare) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TxnCompare) GetOp() TxnCompareOp {
	if x != nil {
		return x.Op
	}
	return TxnCompareOp_TXN_COMPARE_EQUAL
}

func (x *TxnCompare) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type TxnOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          TxnOpType              `protobuf:"varint,1,opt,name=type,proto3,enum=commandpb.TxnOpType" json:"type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	LeaseId       int64                  `protobuf:"varint,4,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnOp) Reset() {
	*x = TxnOp{}
	mi := &file_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnOp) ProtoMessage() {}

func (x *TxnOp) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnOp.ProtoReflect.Descriptor instead.
func (*TxnOp) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{2}
}

func (x *TxnOp) GetType() TxnOpType {
	if x != nil {
		return x.Type
	}
	return TxnOpType_TXN_OP_GET
}

func (x *TxnOp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TxnOp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TxnOp) GetLeaseId() int64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

type TxnCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compares      []*TxnCompare          `protobuf:"bytes,1,rep,name=compares,proto3" json:"compares,omitempty"`
	ThenOps       []*TxnOp               `protobuf:"bytes,2,rep,name=then_ops,json=thenOps,proto3" json:"then_ops,omitempty"`
	ElseOps       []*TxnOp               `protobuf:"bytes,3,rep,name=else_ops,json=elseOps,proto3" json:"else_ops,omitempty"`
	ClientId      int64                  `protobuf:"varint,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           int64                  `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnCommand) Reset() {
	*x = TxnCommand{}
	mi := &file_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnCommand) ProtoMessage() {}

func (x *TxnCommand) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnCommand.ProtoReflect.Descriptor instead.
func (*TxnCommand) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{3}
}

func (x *TxnCommand) GetCompares() []*TxnCompare {
	if x != nil {
		return x.Compares
	}
	return nil
}

func (x *TxnCommand) GetThenOps() []*TxnOp {
	if x != nil {
		return x.ThenOps
	}
	return nil
}

func (x *TxnCommand) GetElseOps() []*TxnOp {
	if x != nil {
		return x.ElseOps
	}
	return nil
}

func (x *TxnCommand) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *TxnCommand) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type LeaseGrantCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ttl           int64                  `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseGrantCommand) Reset() {
	*x = LeaseGrantCommand{}
	mi := &file_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseGrantCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseGrantCommand) ProtoMessage() {}

func (x *LeaseGrantCommand) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseGrantCommand.ProtoReflect.Descriptor instead.
func (*LeaseGrantCommand) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{4}
}

func (x *LeaseGrantCommand) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *LeaseGrantCommand) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *LeaseGrantCommand) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type LeaseRevokeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRevokeCommand) Reset() {
	*x = LeaseRevokeCommand{}
	mi := &file_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRevokeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRevokeCommand) ProtoMessage() {}

func (x *LeaseRevokeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRevokeCommand.ProtoReflect.Descriptor instead.
func (*LeaseRevokeCommand) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{5}
}

func (x *LeaseRevokeCommand) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LeaseRevokeCommand) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *LeaseRevokeCommand) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type LeaseKeepAliveCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseKeepAliveCommand) Reset() {
	*x = LeaseKeepAliveCommand{}
	mi := &file_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseKeepAliveCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseKeepAliveCommand) ProtoMessage() {}

func (x *LeaseKeepAliveCommand) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseKeepAliveCommand.ProtoReflect.Descriptor instead.
func (*LeaseKeepAliveCommand) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{6}
}

func (x *LeaseKeepAliveCommand) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LeaseKeepAliveCommand) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *LeaseKeepAliveCommand) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  Kind                   `protobuf:"varint,1,opt,name=kind,proto3,enum=commandpb.Kind" json:"kind,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Command_Kv
	//	*Command_Txn
	//	*Command_LeaseGrant
	//	*Command_LeaseRevoke
	//	*Command_LeaseKeepalive
	Body          isCommand_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{7}
}

func (x *Command) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_KV
}

func (x *Command) GetBody() isCommand_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Command) GetKv() *KVCommand {
	if x != nil {
		if x, ok := x.Body.(*Command_Kv); ok {
			return x.Kv
		}
	}
	return nil
}

func (x *Command) GetTxn() *TxnCommand {
	if x != nil {
		if x, ok := x.Body.(*Command_Txn); ok {
			return x.Txn
		}
	}
	return nil
}

func (x *Command) GetLeaseGrant() *LeaseGrantCommand {
	if x != nil {
		if x, ok := x.Body.(*Command_LeaseGrant); ok {
			return x.LeaseGrant
		}
	}
	return nil
}

func (x *Command) GetLeaseRevoke() *LeaseRevokeCommand {
	if x != nil {
		if x, ok := x.Body.(*Command_LeaseRevoke); ok {
			return x.LeaseRevoke
		}
	}
	return nil
}

func (x *Command) GetLeaseKeepalive() *LeaseKeepAliveCommand {
	if x != nil {
		if x, ok := x.Body.(*Command_LeaseKeepalive); ok {
			return x.LeaseKeepalive
		}
	}
	return nil
}

type isCommand_Body interface {
	isCommand_Body()
}

type Command_Kv struct {
	Kv *KVCommand `protobuf:"bytes,2,opt,name=kv,proto3,oneof"`
}

type Command_Txn struct {
	Txn *TxnCommand `protobuf:"bytes,3,opt,name=txn,proto3,oneof"`
}

type Command_LeaseGrant struct {
	LeaseGrant *LeaseGrantCommand `protobuf:"bytes,4,opt,name=lease_grant,json=leaseGrant,proto3,oneof"`
}

type Command_LeaseRevoke struct {
	LeaseRevoke *LeaseRevokeCommand `protobuf:"bytes,5,opt,name=lease_revoke,json=leaseRevoke,proto3,oneof"`
}

type Command_LeaseKeepalive struct {
	LeaseKeepalive *LeaseKeepAliveCommand `protobuf:"bytes,6,opt,name=lease_keepalive,json=leaseKeepalive,proto3,oneof"`
}

func (*Command_Kv) isCommand_Body() {}

func (*Command_Txn) isCommand_Body() {}

func (*Command_LeaseGrant) isCommand_Body() {}

func (*Command_LeaseRevoke) isCommand_Body() {}

func (*Command_LeaseKeepalive) isCommand_Body() {}

var File_command_proto protoreflect.FileDescriptor

const file_command_proto_rawDesc = "" +
	"\n" +
	"\rcommand.proto\x12\tcommandpb\"\xb6\x01\n" +
	"\tKVCommand\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.commandpb.KVTypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\x03R\bclientId\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x03R\x03seq\x12\x10\n" +
	"\x03rev\x18\x06 \x01(\x03R\x03rev\x12\x19\n" +
	"\blease_id\x18\a \x01(\x03R\aleaseId\"c\n" +
	"\n" +
	"TxnCompare\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x02op\x18\x02 \x01(\x0e2\x17.commandpb.TxnCompareOpR\x02op\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\"t\n" +
	"\x05TxnOp\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.commandpb.TxnOpTypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x19\n" +
	"\blease_id\x18\x04 \x01(\x03R\aleaseId\"\xc8\x01\n" +
	"\n" +
	"TxnCommand\x121\n" +
	"\bcompares\x18\x01 \x03(\v2\x15.commandpb.TxnCompareR\bcompares\x12+\n" +
	"\bthen_ops\x18\x02 \x03(\v2\x10.commandpb.TxnOpR\athenOps\x12+\n" +
	"\belse_ops\x18\x03 \x03(\v2\x10.commandpb.TxnOpR\aelseOps\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\x03R\bclientId\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x03R\x03seq\"T\n" +
	"\x11LeaseGrantCommand\x12\x10\n" +
	"\x03ttl\x18\x01 \x01(\x03R\x03ttl\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\"S\n" +
	"\x12LeaseRevokeCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\"V\n" +
	"\x15LeaseKeepAliveCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\"\xdb\x02\n" +
	"\aCommand\x12#\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x0f.commandpb.KindR\x04kind\x12&\n" +
	"\x02kv\x18\x02 \x01(\v2\x14.commandpb.KVCommandH\x00R\x02kv\x12)\n" +
	"\x03txn\x18\x03 \x01(\v2\x15.commandpb.TxnCommandH\x00R\x03txn\x12?\n" +
	"\vlease_grant\x18\x04 \x01(\v2\x1c.commandpb.LeaseGrantCommandH\x00R\n" +
	"leaseGrant\x12B\n" +
	"\flease_revoke\x18\x05 \x01(\v2\x1d.commandpb.LeaseRevokeCommandH\x00R\vleaseRevoke\x12K\n" +
	"\x0flease_keepalive\x18\x06 \x01(\v2 .commandpb.LeaseKeepAliveCommandH\x00R\x0eleaseKeepaliveB\x06\n" +
	"\x04body*h\n" +
	"\x04Kind\x12\v\n" +
	"\aKIND_KV\x10\x00\x12\f\n" +
	"\bKIND_TXN\x10\x01\x12\x14\n" +
	"\x10KIND_LEASE_GRANT\x10\x02\x12\x15\n" +
	"\x11KIND_LEASE_REVOKE\x10\x03\x12\x18\n" +
	"\x14KIND_LEASE_KEEPALIVE\x10\x04*/\n" +
	"\x06KVType\x12\n" +
	"\n" +
	"\x06KV_PUT\x10\x00\x12\n" +
	"\n" +
	"\x06KV_GET\x10\x01\x12\r\n" +
	"\tKV_DELETE\x10\x02*T\n" +
	"\fTxnCompareOp\x12\x15\n" +
	"\x11TXN_COMPARE_EQUAL\x10\x00\x12\x17\n" +
	"\x13TXN_COMPARE_GREATER\x10\x01\x12\x14\n" +
	"\x10TXN_COMPARE_LESS\x10\x02*>\n" +
	"\tTxnOpType\x12\x0e\n" +
	"\n" +
	"TXN_OP_GET\x10\x00\x12\x0e\n" +
	"\n" +
	"TXN_OP_PUT\x10\x01\x12\x11\n" +
	"\rTXN_OP_DELETE\x10\x02B(Z&etcd-KV/internal/pb/command; commandpbb\x06proto3"

var (
	file_command_proto_rawDescOnce sync.Once
	file_command_proto_rawDescData []byte
)

func file_command_proto_rawDescGZIP() []byte {
	file_command_proto_rawDescOnce.Do(func() {
		file_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)))
	})
	return file_command_proto_rawDescData
}

var file_command_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_command_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_command_proto_goTypes = []any{
	(Kind)(0),                     // 0: commandpb.Kind
	(KVType)(0),                   // 1: commandpb.KVType
	(TxnCompareOp)(0),             // 2: commandpb.TxnCompareOp
	(TxnOpType)(0),                // 3: commandpb.TxnOpType
	(*KVCommand)(nil),             // 4: commandpb.KVCommand
	(*TxnCompare)(nil),            // 5: commandpb.TxnCompare
	(*TxnOp)(nil),                 // 6: commandpb.TxnOp
	(*TxnCommand)(nil),            // 7: commandpb.TxnCommand
	(*LeaseGrantCommand)(nil),     // 8: commandpb.LeaseGrantCommand
	(*LeaseRevokeCommand)(nil),    // 9: commandpb.LeaseRevokeCommand
	(*LeaseKeepAliveCommand)(nil), // 10: commandpb.LeaseKeepAliveCommand
	(*Command)(nil),               // 11: commandpb.Command
}
var file_command_proto_depIdxs = []int32{
	1,  // 0: commandpb.KVCommand.type:type_name -> commandpb.KVType
	2,  // 1: commandpb.TxnCompare.op:type_name -> commandpb.TxnCompareOp
	3,  // 2: commandpb.TxnOp.type:type_name -> commandpb.TxnOpType
	5,  // 3: commandpb.TxnCommand.compares:type_name -> commandpb.TxnCompare
	6,  // 4: commandpb.TxnCommand.then_ops:type_name -> commandpb.TxnOp
	6,  // 5: commandpb.TxnCommand.else_ops:type_name -> commandpb.TxnOp
	0,  // 6: commandpb.Command.kind:type_name -> commandpb.Kind
	4,  // 7: commandpb.Command.kv:type_name -> commandpb.KVCommand
	7,  // 8: commandpb.Command.txn:type_name -> commandpb.TxnCommand
	8,  // 9: commandpb.Command.lease_grant:type_name -> commandpb.LeaseGrantCommand
	9,  // 10: commandpb.Command.lease_revoke:type_name -> commandpb.LeaseRevokeCommand
	10, // 11: commandpb.Command.lease_keepalive:type_name -> commandpb.LeaseKeepAliveCommand
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_command_proto_init() }
func file_command_proto_init() {
	if File_command_proto != nil {
		return
	}
	file_command_proto_msgTypes[7].OneofWrappers = []any{
		(*Command_Kv)(nil),
		(*Command_Txn)(nil),
		(*Command_LeaseGrant)(nil),
		(*Command_LeaseRevoke)(nil),
		(*Command_LeaseKeepalive)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_command_proto_goTypes,
		DependencyIndexes: file_command_proto_depIdxs,
		EnumInfos:         file_command_proto_enumTypes,
		MessageInfos:      file_command_proto_msgTypes,
	}.Build()
	File_command_proto = out.File
	file_command_proto_goTypes = nil
	file_command_proto_depIdxs = nil
}
